-- paste icons from http://fontawesome.io/cheatsheet/
local M = {
	arrow_circle_left		= "",
	angle_double_left		= "",
	angle_left				= "",
	arrow_circle_o_left 	= "",
	arrow_left 				= "",
	backward				= "",
	bell 					= "",
	bullseye 				= "",
	burger 					= "", -- same as reorder
	camera 					= "",
	caret_left 				= "",
	chevron_circle_left		= "",
	chevron_left 			= "",
	clock 					= "",
	cog 					= "",
	comment 				= "",
	copyright 				= "",
	crosshairs 				= "",
	ellipsis				= "",
	ellipsis_v 				= "",
	eraser 					= "",
	font 					= "",
	gear 					= "",
	home 					= "",
	info_circle 			= "",
	image 					= "",
	list 					= "",
	music 					= "",
	navicon 				= "",
	paint_brush 			= "",
	paperclip				= "",
	pencil 					= "",
	pencil_square_o 		= "",
	play 					= "",
	play_circle 			= "",
	plus_square_o 			= "",
	question_circle 		= "",
	random 					= "",
	redo 					= "",
	reorder 				= "",
	search      			= "",
	sign_out 				= "",
	spinner 				= "",
	undo 					= "",
	user 					= ""

}

return M